blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation & Lit.dev
    url: https://github.com/lit/lit.dev/issues/
    about: For bugs or features related to the content on lit.dev, please file an issue on the lit.dev repo.

  - name: â“ Questions, Help, Support
    url: https://github.com/lit/lit/discussions
    about: If you have a question about using Lit, please see the Discussions board.
