blank_issues_enabled: false
contact_links:
  - name: Documentation & Lit.dev
    url: https://github.com/lit/lit.dev/issues/
    about: For bugs or features related to the content on lit.dev, please file an issue on the lit.dev repo.

  - name: Discussions
    url: https://github.com/lit/lit/discussions
    about: For questions, support, new project ideas, or project sharing, please see the discussions board.
